---
title: "trial results"
author: "Allen Yeh"
output:
  html_document: default
  pdf_document: default
---

```
```

```{r warning=FALSE}
library(tidyverse)
library(gmodels)
library(rstatix)
library(ggplot2)
library(ez)
```

### Import data

#### Read the csv file and claim the data type
```{r}

participant_id = c("2", "3", "4", "5", "6", "8", "9", "11", "12", "13", "15", "16", "18", "19", "20", "23")
word_length = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11")

trial_log <- read_csv("logs/result.csv", col_types = cols(
  pid = col_factor(levels = participant_id),
  tid = col_integer(),
  wpm = col_double(),
  corrected_word = col_integer(),
  uncorrected_error = col_integer(),
  corrected_error = col_integer(),
  uwer = col_double(),
  cwer = col_double(),
))

usage_log <- read_csv("logs/usage.csv", col_types = cols(
  pid = col_factor(levels = participant_id),
  swipeTyping_usage = col_double(),
))%>%
  mutate(
    type = "swipe",
      )

tap_log <- read_csv("logs/usage.csv", col_types = cols(
  pid = col_factor(levels = participant_id),
  swipeTyping_usage = col_double(),
))%>%
  mutate(
    usage = 1 - swipeTyping_usage,
    type = "tap",
      )

colnames(usage_log)[2] <- "usage"

usage_log <- rbind(usage_log, select(tap_log, c("pid", "usage", "type")))

word_log <- read_csv("logs/word.csv", col_types = cols(
  pid = col_factor(levels = participant_id),
  target = col_character(),
  word = col_character(),
  count = col_factor(levels = word_length),
  insert_start_time = col_datetime(format = "%Y-%m-%d %H:%M:%OS"),
  insert_end_time = col_datetime(format = "%Y-%m-%d %H:%M:%OS"),
  category = col_factor(levels = c("top1", "top3", "incorrect")),
  swipe_ratio = col_double(),
  tap_ratio = col_double(),
  swipe_key_count = col_integer(),
  tap_key_count = col_integer(),
  swipe_dist = col_character(),
  swipe_key_set = col_character(),
)) %>%
  mutate(
    time = as.numeric(insert_end_time - insert_start_time),
    usage = ifelse(tap_ratio == 1, "tap", "swipe"),
    type_key_count = swipe_key_count+tap_key_count,
    is_match = ifelse(nchar(target) == type_key_count, TRUE, FALSE),
      )

swipe_log <- read_csv("logs/swipes.csv", col_types = cols(
  distance = col_double(),
  target_distance = col_double(),
  target_start_key = col_character(),
  target_end_key = col_character(),
)) %>%
  mutate(
    target_dist_bin = ceiling(target_distance),
      )


```

### functions

```{r warning=FALSE}
percent <- function(num, digits = 2, ...) {      
  percentage <-formatC(num * 100, format = "f", digits = digits, ...)
  
  # appending "%" symbol at the end of
  # calculate percentage value
  paste0(percentage, "%")
}
```

### Total

#### word per seoncd
```{r warning=FALSE}

trial_wpm <-trial_log %>%
  summarize(
    meanWPM = wpm %>% mean(na.rm=TRUE),
    lowCIWPM = ci(wpm)[2]%>% pmax(0),
    highCIWPM = ci(wpm)[3],
    sdWPM = ci(wpm)[4],
    stdWPM = wpm %>% sd())

trial_wpm

trial_uwer <-trial_log %>%
  summarize(
    meanuwer = uwer %>% mean(na.rm=TRUE),
    lowCIuwer = ci(uwer)[2]%>% pmax(0),
    highCIuwer = ci(uwer)[3],
    sduwer = ci(uwer)[4],
    stduwer = uwer %>% sd())

trial_uwer

trial_cwer <-trial_log %>%
  summarize(
    meacuwer = cwer %>% mean(na.rm=TRUE),
    lowCIcwer = ci(cwer)[2]%>% pmax(0),
    highCIcwer = ci(cwer)[3],
    sdcwer = ci(cwer)[4],
    stdcwer = cwer %>% sd())

trial_cwer





```


### Swipe Typing Usage

#### participant

```{r warning=FALSE}

usage_participant_graph <- ggplot(usage_log, aes(fill=type, y=usage, x=pid, label = percent(usage, 1))) + 
  geom_bar(position=position_stack(reverse = TRUE), stat="identity", width=0.5) +
  geom_text(size = 3, position = position_stack(reverse = TRUE, vjust = 0.5)) +
  scale_fill_discrete(breaks = c('tap', 'swipe')) +
  scale_fill_manual(values = c('tap' = "#2ECC71", 'swipe' = "#3498DB"))

usage_participant_graph

usage_participant_graph + theme( # remove the vertical grid lines
          panel.background = element_blank(),
          panel.grid.major.y = element_line( size=.1, color="gray" ),
          # explicitly set the horizontal lines (or they will disappear too)
          panel.grid.major.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y = element_blank()
    )

ggsave("usage participant.pdf", width = 20, height = 10, limitsize = FALSE)


```
#### char count

```{r warning=FALSE}

word_count <- word_log %>% 
  group_by(count, usage, .drop = FALSE) %>% count()

word_count_summary <- word_count %>% 
  group_by(count) %>%
  summarize(
    ratio = n / sum(n),
    n_trials = sum(n),
    usage = usage,
    n = n,
  ) %>%
  ungroup()

usage_word_graph <- ggplot(word_count_summary, aes(fill=usage, y=ratio, x=count, label = percent(ratio, 1))) + 
  geom_bar(position=position_stack(reverse = TRUE), stat="identity", width=0.5) +
  geom_text(size = 3, position = position_stack(reverse = TRUE, vjust = 0.5)) +
  scale_fill_discrete(breaks = c('tap', 'swipe')) +
  scale_fill_manual(values = c('tap' = "#2ECC71", 'swipe' = "#3498DB"))

usage_word_graph


usage_word_graph + theme( # remove the vertical grid lines
          panel.background = element_blank(),
          panel.grid.major.y = element_line( size=.1, color="gray" ),
          # explicitly set the horizontal lines (or they will disappear too)
          panel.grid.major.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y = element_blank()
    )

ggsave("usage word.pdf", width = 11, height = 10, limitsize = FALSE)


```

### word

#### accuracy
```{r warning=FALSE}

word_accuracy <- word_log %>% 
  group_by(count, category, .drop = FALSE) %>% count()

word_accuracy_summary <-word_accuracy %>%
  group_by(count) %>%
  summarize(
    ratio = n / sum(n),
    n_trials = sum(n),
    category = category,
    n = n,
    )%>%
  ungroup()

word_accuracy_summary

word_accuracy_summary_top1 <-word_accuracy_summary %>%
  filter(category == 'top1') %>%
  group_by(count) %>%
  summarize(
    top1_accuracy = sum(ratio),
    )

word_accuracy_summary_top3 <-word_accuracy_summary %>%
  filter(category == 'top1' | category == 'top3') %>%
  group_by(count) %>%
  summarize(
    top3_accuracy = sum(ratio),
    )

word_accuracy <- left_join(word_accuracy_summary_top1, word_accuracy_summary_top3, by = "count") 
word_accuracy

```

#### time
```{r warning=FALSE}

word_time_summary <-word_log %>%
  filter(category == 'top1' | category == 'top3' | is_match) %>%
  group_by(count, usage) %>%
  summarize(
    meanTime = time %>% mean(na.rm=TRUE),
    lowCITime = ci(time)[2]%>% pmax(0),
    highCITime = ci(time)[3],
    sdTime = ci(time)[4],
    stdTime = time %>% sd()) %>%
  ungroup()

word_time_summary

# line + dot
word_time_graph <- ggplot(word_time_summary) +
  geom_pointrange( aes(x=count, y=meanTime, ymin=lowCITime, ymax=highCITime,color=reorder(usage, desc(usage))), alpha=0.9, size=0.8, position=position_dodge(width=1.0)) +
  scale_y_continuous(limits=c(0.0,9.0)) +
  scale_colour_manual(values = c("swipe" = "#3498DB", "tap" = "#2ECC71"))

word_time_graph

word_time_graph + theme( # remove the vertical grid lines
          panel.background = element_blank(),
          panel.grid.major.y = element_line( size=.1, color="gray" ),
          # explicitly set the horizontal lines (or they will disappear too)
          panel.grid.major.x = element_line( size=.1, color="gray" ),
          axis.title.x = element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y = element_blank()
    )

ggsave("time usage count.pdf", width = 11, height = 10)
```

#### within swipe
##### swipe-tap ratio (key count)
```{r warning=FALSE}

word_swipe <-word_log %>%
  filter(usage == 'swipe') %>%
  filter(category == 'top1' | category == 'top3') %>%
  filter(is_match)

word_swipe_ratio_summary <-word_swipe %>%
  group_by(count) %>%
  summarize(
    meanRatio = swipe_ratio %>% mean(na.rm=TRUE),
    lowCIRatio = ci(swipe_ratio)[2]%>% pmax(0),
    highCIRatio = ci(swipe_ratio)[3]%>% pmin(1),
    sdRatio = ci(swipe_ratio)[4],
    stdRatio = swipe_ratio %>% sd()) %>%
  ungroup()

word_swipe_ratio_summary


word_swipe_key_summary <-word_swipe %>%
  group_by(count) %>%
  summarize(
    meanRatio = swipe_key_count %>% mean(na.rm=TRUE),
    lowCIRatio = ci(swipe_key_count)[2]%>% pmax(0),
    highCIRatio = ci(swipe_key_count)[3],
    sdRatio = ci(swipe_key_count)[4],
    stdRatio = swipe_key_count %>% sd()) %>%
  ungroup()

word_swipe_key_summary
```

##### swipe distance

```{r warning=FALSE}


swipe_dist <- swipe_log %>%
  summarize(
    meanDist = distance %>% mean(na.rm=TRUE),
    lowCIDist = ci(distance)[2]%>% pmax(0),
    highCIDist = ci(distance)[3],
    sdDist = ci(distance)[4],
    stdDist = distance %>% sd())

swipe_dist

swipe_target_dist <- swipe_log %>%
  summarize(
    meanDist = target_distance %>% mean(na.rm=TRUE),
    lowCIDist = ci(target_distance)[2]%>% pmax(0),
    highCIDist = ci(target_distance)[3],
    sdDist = ci(target_distance)[4],
    stdDist = target_distance %>% sd())

swipe_target_dist

swipe_bin_count <- swipe_log %>% 
  group_by(target_dist_bin) %>% count()
swipe_bin_count

swipe_dist_bin <- swipe_log %>%
  group_by(target_dist_bin) %>%
  summarize(
    meanDist = distance %>% mean(na.rm=TRUE),
    lowCIDist = ci(distance)[2]%>% pmax(0),
    highCIDist = ci(distance)[3],
    sdDist = ci(distance)[4],
    stdDist = distance %>% sd()) %>%
  ungroup()

swipe_dist_bin

swipe_target_dist_bin <- swipe_log %>%
  group_by(target_dist_bin) %>%
  summarize(
    meanTDist = target_distance %>% mean(na.rm=TRUE),
    lowCITDist = ci(target_distance)[2]%>% pmax(0),
    highCITDist = ci(target_distance)[3],
    sdTDist = ci(target_distance)[4],
    stdTDist = target_distance %>% sd())%>%
  ungroup()

swipe_target_dist_bin

swipe_target_dist_res <- swipe_bin_count %>%
  left_join(swipe_dist_bin) %>%
  left_join(swipe_target_dist_bin) %>%
  select(target_dist_bin, n, meanDist, meanTDist)

swipe_target_dist_res

```